### ISSUE TITLE
Where are the compiled .st3plugin files?

### ISSUE THREAD

**Issue by vmiceli** [mechgt/training-load#1]
Hello Mechgt. I was a user of your Training Load and gear plugin, Is there a way to get the st3plugin file? Or can I compile it with Visual Studio? Thanks a million!!

**Comment by mechgt** [comment]
All of the compiled (.st3plugin) files are posted in the Releases tab on github.  Here's the link for Training Load:  https://github.com/mechgt/training-load/releases

**Comment by tsofron** [comment]
Hello Mechgt - first - thanks for all your plugins! It was a good time for Sporttracks :(. One thing i would kindly ask you - by any chance, do you have the opensourcemap plugin and could share it with me? :D...Thanks a lot, Tudor (tsofron@hotmail.com)
