### ISSUE TITLE
ST3 help 

### ISSUE THREAD

**Issue by tsofron** [mechgt/training-load#2]
Hello Mechgt - first - thanks for all your plugins! It was a good time for Sporttracks :(. One thing i would kindly ask you - by any chance, do you have the opensourcemap plugin and could share it with me? :D...Thanks a lot, Tudor (tsofron@hotmail.com). 
PS: You can definitely close the 'issue' :D, but i thought this way you'll get a notification

**Comment by mechgt** [comment]
No, sorry I don't have that.
